# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(387, 753)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color:     #2F4F4F")
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 961, 281))
        self.frame.setStyleSheet("background-color:#FFF")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(50, 60, 281, 71))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei Light")
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(70, 140, 241, 71))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei Light")
        font.setPointSize(28)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.switch_providers = QtWidgets.QComboBox(self.frame)
        self.switch_providers.setGeometry(QtCore.QRect(20, 210, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(20)
        self.switch_providers.setFont(font)
        self.switch_providers.setObjectName("comboBox")
        self.first_currency = QtWidgets.QLineEdit(self.centralwidget)
        self.first_currency.setGeometry(QtCore.QRect(10, 300, 361, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(26)
        self.first_currency.setFont(font)
        self.first_currency.setStyleSheet("background-color: #fff;\n"
                                                    "border: 30px;\n"
                                                    "color: green;\n"
                                                    "")
        self.first_currency.setText("")
        self.first_currency.setObjectName("lineEdit")
        self.second_currency = QtWidgets.QLineEdit(self.centralwidget)
        self.second_currency.setGeometry(QtCore.QRect(10, 460, 361, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(26)
        self.second_currency.setFont(font)
        self.second_currency.setStyleSheet("background-color: #fff;\n"
                                                    "border: 30px;\n"
                                                    "color: green;\n"
                                                    "text-align: center;\n"
                                                    "\n"
                                                    "")
        self.second_currency.setText("")
        self.second_currency.setObjectName("lineEdit_2")
        self.money = QtWidgets.QLineEdit(self.centralwidget)
        self.money.setGeometry(QtCore.QRect(10, 380, 361, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(26)
        self.money.setFont(font)
        self.money.setStyleSheet("background-color: #fff;\n"
                                            "border: 30px;\n"
                                            "color: green;\n"
                                            "")
        self.money.setText("")
        self.money.setObjectName("lineEdit_3")
        self.button_convert = QtWidgets.QPushButton(self.centralwidget)
        self.button_convert.setGeometry(QtCore.QRect(10, 630, 351, 91))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei Light")
        font.setPointSize(28)
        self.button_convert.setFont(font)
        self.button_convert.setStyleSheet("background-color:3")
        self.button_convert.setObjectName("pushButton")
        self.converted = QtWidgets.QLineEdit(self.centralwidget)
        self.converted.setGeometry(QtCore.QRect(10, 540, 361, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(26)
        self.converted.setFont(font)
        self.converted.setStyleSheet("background-color: #fff;\n"
                                                "border: 30px;\n"
                                                "color: green;\n"
                                                "")
        self.converted.setText("")
        self.converted.setObjectName("lineEdit_5")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "CONVERTER"))
        self.label_2.setText(_translate("MainWindow", "CURRENCY"))
        self.button_convert.setText(_translate("MainWindow", "CONVERTER"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
